on:
  push:
    branches:
      - master

jobs:
  deploy-to-compose-deploy:
    runs-on: ubuntu-latest
    name: ComposeDeploy
    steps:
      - uses: actions/checkout@v4
      - id: ComposeDeploy
        uses: lukasvdberk/compose-deploy-action@master
        env:
          API_KEY: ${{ secrets.COMPOSE_DEPLOY_API_KEY }}
        with:
          project-id: '270408203'
          docker-compose-file: 'docker-compose.yml'
    
